
const data = [{ name: '精白', hex: '#ffffff' },
  { name: '银白', hex: '#e9e7ef' },
  { name: '铅白', hex: '#f0f0f4' },
  { name: '霜色', hex: '#e9f1f6' },
  { name: '雪白', hex: '#f0fcff' },
  { name: '莹白', hex: '#e3f9fd' },
  { name: '月白', hex: '#d6ecf0' },
  { name: '象牙白', hex: '#fffbf0' },
  { name: '缟', hex: '#f2ecde' },
  { name: '鱼肚白', hex: '#fcefe8' },
  { name: '白粉', hex: '#fff2fd' },
  { name: '茶白', hex: '#f3f9f1' },
  { name: '鸭卵青', hex: '#e0eee8' },
  { name: '素', hex: '#e0f0e9' },
  { name: '青白', hex: '#c0ebd7' },
  { name: '蟹壳青', hex: '#bbcdc5' },
  { name: '花白', hex: '#c2ccd0' },
  { name: '老银', hex: '#bacac6' },
  { name: '灰色', hex: '#808080' },
  { name: '苍色', hex: '#75878a' },
  { name: '水色', hex: '#88ada6' },
  { name: '樱草色', hex: '#eaff56' },
  { name: '鹅黄', hex: '#fff143' },
  { name: '鸭黄', hex: '#faff72' },
  { name: '杏黄', hex: '#ffa631' },
  { name: '橙黄', hex: '#ffa400' },
  { name: '橙色', hex: '#fa8c35' },
  { name: '杏红', hex: '#ff8c31' },
  { name: '橘黄', hex: '#ff8936' },
  { name: '橘红', hex: '#ff7500' },
  { name: '藤黄', hex: '#ffb61e' },
  { name: '姜黄', hex: '#ffc773' },
  { name: '雌黄', hex: '#ffc64b' },
  { name: '赤金', hex: '#f2be45' },
  { name: '缃色', hex: '#f0c239' },
  { name: '雄黄', hex: '#e9bb1d' },
  { name: '秋香色', hex: '#d9b611' },
  { name: '金色', hex: '#eacd76' },
  { name: '牙色', hex: '#eedeb0' },
  { name: '枯黄', hex: '#d3b17d' },
  { name: '黄栌', hex: '#e29c45' },
  { name: '乌金', hex: '#a78e44' }]

export default data
